// BITZ-ITC-main/vue-website/bitz/src/components/layout/Header.vue
<template>
  <header 
    :class="[
      'fixed top-0 left-0 right-0 z-50 transition-all duration-300',
      isScrolled ? 'bg-white/95 backdrop-blur-md shadow-lg' : 'bg-transparent'
    ]"
  >
    <nav class="container-custom">
      <div class="flex items-center justify-between h-16 px-4">
        <!-- Logo -->
        <router-link 
          to="/" 
          class="flex items-center space-x-2 text-2xl font-bold"
          :class="isScrolled ? 'text-navy-900' : 'text-white'"
        >
          <img src="/logo.svg" alt="BITZ" class="h-8 w-auto" />
          <span>bitz</span>
        </router-link>

        <!-- Desktop Navigation -->
        <div class="hidden md:flex items-center space-x-8">
          <router-link
            v-for="item in navigationItems"
            :key="item.name"
            :to="item.path"
            :class="[
              'text-sm font-medium transition-colors duration-300 hover:text-primary-500',
              isScrolled ? 'text-gray-700' : 'text-white',
              $route.path === item.path ? 'text-primary-500' : ''
            ]"
          >
            {{ item.name }}
          </router-link>
        </div>

        <!-- Theme Toggle & Mobile Menu Button -->
        <div class="flex items-center space-x-4">
          <!-- Theme Toggle -->
          <button
            @click="toggleDarkMode"
            :class="[
              'p-2 rounded-lg transition-colors duration-300',
              isScrolled ? 'text-gray-700 hover:bg-gray-100' : 'text-white hover:bg-white/10'
            ]"
          >
            <Sun v-if="isDark" :size="20" />
            <Moon v-else :size="20" />
          </button>

          <!-- Mobile Menu Button -->
          <button
            @click="toggleMobileMenu"
            :class="[
              'md:hidden p-2 rounded-lg transition-colors duration-300',
              isScrolled ? 'text-gray-700 hover:bg-gray-100' : 'text-white hover:bg-white/10'
            ]"
          >
            <Menu v-if="!isMobileMenuOpen" :size="24" />
            <X v-else :size="24" />
          </button>
        </div>
      </div>

      <!-- Mobile Navigation -->
      <Transition name="mobile-menu">
        <div
          v-if="isMobileMenuOpen"
          class="md:hidden bg-white border-t border-gray-200 shadow-lg"
        >
          <div class="px-4 py-6 space-y-4">
            <router-link
              v-for="item in navigationItems"
              :key="item.name"
              :to="item.path"
              @click="closeMobileMenu"
              :class="[
                'block text-base font-medium text-gray-700 hover:text-primary-500 transition-colors duration-300',
                $route.path === item.path ? 'text-primary-500' : ''
              ]"
            >
              {{ item.name }}
            </router-link>
          </div>
        </div>
      </Transition>
    </nav>
  </header>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import { Menu, X, Sun, Moon } from 'lucide-vue-next'
import { useSiteStore } from '@/stores/siteStore'
import { useDarkMode } from '@/composables/useDarkMode'
import { useScroll } from '@/composables/useScroll'

const route = useRoute()
const siteStore = useSiteStore()
const { isDark, toggleDarkMode } = useDarkMode()
const { isScrolled } = useScroll()

const isMobileMenuOpen = ref(false)
const { navigationItems } = siteStore

const toggleMobileMenu = () => {
  isMobileMenuOpen.value = !isMobileMenuOpen.value
}

const closeMobileMenu = () => {
  isMobileMenuOpen.value = false
}

// Close mobile menu on route change
const handleRouteChange = () => {
  closeMobileMenu()
}

onMounted(() => {
  // Watch for route changes to close mobile menu
  route && route.path && handleRouteChange()
})
</script>

<style scoped>
.mobile-menu-enter-active,
.mobile-menu-leave-active {
  transition: all 0.3s ease;
}

.mobile-menu-enter-from,
.mobile-menu-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>

// BITZ-ITC-main/components/header.tsx
'use client';

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { LayoutGrid, Moon, Sun } from 'lucide-react';
import { useTheme } from "next-themes";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { ThemeToggleSwitch } from "@/components/ui/theme-toggle-switch";
import Image from 'next/image';

export default function Header() {
  const { theme, setTheme } = useTheme();
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  return (
    <header className="sticky top-0 z-50 w-full border-b bg-white dark:bg-navy-950 backdrop-blur-lg bg-white/50 dark:bg-navy/50 px-4 md:px-6">
      <div className="container flex items-center justify-between h-16 mx-auto">
        <Link href="/" className="flex items-center gap-2">
          <div className="flex items-center gap-2">
            <Image 
              src="/Bitz logo.png" 
              alt="BITZ-itc Logo" 
              width={60} 
              height={60} 
              className="object-contain"
              priority
            />
          </div>
        </Link>
        <nav className="hidden md:flex gap-6">
          <Link href="/" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200">
            Home
          </Link>
          <Link href="/our-vision" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200">
            Our Vision
          </Link>
          <Link href="/services" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200">
            Services
          </Link>
          <Link href="/projects" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200">
            Projects
          </Link>
          <Link href="/team" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200">
            Our Team
          </Link>
          <Link href="/contact" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200">
            Contact
          </Link>
        </nav>
        <div className="flex items-center gap-4">
          <ThemeToggleSwitch />
          <Button variant="outline" size="icon" className="md:hidden rounded-full" onClick={toggleMobileMenu}>
            <LayoutGrid className="h-5 w-5" />
            <span className="sr-only">Toggle menu</span>
          </Button>
        </div>
      </div>

      {/* Mobile Menu */}
      <div className={cn("md:hidden bg-white dark:bg-navy-950", isMobileMenuOpen ? 'block' : 'hidden')}>
        <nav className="flex flex-col items-center space-y-4 py-4">
          <Link href="/" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200" onClick={toggleMobileMenu}>
            Home
          </Link>
          <Link href="/our-vision" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200" onClick={toggleMobileMenu}>
            Our Vision
          </Link>
          <Link href="/services" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200" onClick={toggleMobileMenu}>
            Services
          </Link>
          <Link href="/projects" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200" onClick={toggleMobileMenu}>
            Projects
          </Link>
          <Link href="/team" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200" onClick={toggleMobileMenu}>
            Our Team
          </Link>
          <Link href="/contact" className="text-base font-medium hover:text-navy dark:hover:text-white transition-colors duration-200" onClick={toggleMobileMenu}>
            Contact
          </Link>
        </nav>
      </div>
    </header>
  );
}
