// BITZ-ITC-main/vue-website/bitz/src/pages/OurVision.vue
<template>
  <div class="min-h-screen">
    <!-- Hero Section -->
    <section class="bg-slate-900 text-white py-20">
      <div class="max-w-7xl mx-auto px-4 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
        <div>
          <h1 class="text-4xl lg:text-5xl font-bold mb-6">Our Vision</h1>
          <p class="text-lg text-gray-300 leading-relaxed">
            Empowering businesses through innovative technology solutions and digital transformation.
          </p>
        </div>
        <div class="relative">
          <div class="bg-blue-600 rounded-lg p-8 h-64 flex items-center justify-center">
            <Lightbulb :size="96" class="text-white" />
          </div>
          <button class="absolute left-4 top-1/2 transform -translate-y-1/2 text-white hover:text-gray-300">
            <ChevronLeft :size="24" />
          </button>
          <button class="absolute right-4 top-1/2 transform -translate-y-1/2 text-white hover:text-gray-300">
            <ChevronRight :size="24" />
          </button>
        </div>
      </div>
    </section>

    <!-- Mission Section -->
    <section class="py-16">
      <div class="max-w-7xl mx-auto px-4">
        <div class="text-center mb-12">
          <div class="inline-flex items-center px-3 py-1 rounded-full bg-slate-900 text-white text-sm font-medium mb-4">
            Our Mission
          </div>
          <h2 class="text-3xl font-bold mb-4">Transforming Businesses Through Technology</h2>
          <p class="text-gray-600 max-w-2xl mx-auto">
            We are committed to delivering innovative solutions that drive growth and efficiency
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div class="text-center">
            <div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Target :size="32" class="text-blue-600" />
            </div>
            <h3 class="text-xl font-semibold mb-4">Our Goals</h3>
            <p class="text-gray-600">
              To be the leading technology partner for businesses seeking digital transformation
            </p>
          </div>

          <div class="text-center">
            <div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Users :size="32" class="text-blue-600" />
            </div>
            <h3 class="text-xl font-semibold mb-4">Our Values</h3>
            <p class="text-gray-600">Innovation, integrity, and excellence in everything we do</p>
          </div>

          <div class="text-center">
            <div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Globe :size="32" class="text-blue-600" />
            </div>
            <h3 class="text-xl font-semibold mb-4">Our Impact</h3>
            <p class="text-gray-600">Creating lasting positive change in the businesses we serve</p>
          </div>
        </div>
      </div>
    </section>

    <!-- How We Work Section -->
    <section class="py-16 bg-gray-50">
      <div class="max-w-7xl mx-auto px-4 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
        <div>
          <div class="inline-flex items-center px-3 py-1 rounded-full bg-slate-900 text-white text-sm font-medium mb-4">
            Our Approach
          </div>
          <h2 class="text-3xl font-bold mb-6">How We Work</h2>
          <p class="text-gray-600 mb-8">
            Our methodology combines technical expertise with a deep understanding of business needs
          </p>

          <div class="space-y-6">
            <div class="flex items-start space-x-4">
              <div class="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-sm">
                1
              </div>
              <div>
                <h4 class="font-semibold mb-2">Understanding</h4>
                <p class="text-gray-600">Deep dive into your business needs and challenges</p>
              </div>
            </div>

            <div class="flex items-start space-x-4">
              <div class="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-sm">
                2
              </div>
              <div>
                <h4 class="font-semibold mb-2">Strategy</h4>
                <p class="text-gray-600">Develop tailored solutions to address your specific needs</p>
              </div>
            </div>

            <div class="flex items-start space-x-4">
              <div class="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-sm">
                3
              </div>
              <div>
                <h4 class="font-semibold mb-2">Implementation</h4>
                <p class="text-gray-600">Execute solutions with precision and attention to detail</p>
              </div>
            </div>

            <div class="flex items-start space-x-4">
              <div class="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-semibold text-sm">
                4
              </div>
              <div>
                <h4 class="font-semibold mb-2">Support</h4>
                <p class="text-gray-600">Provide ongoing support and optimization</p>
              </div>
            </div>
          </div>
        </div>

        <div class="bg-blue-600 rounded-lg p-8 h-96 flex items-center justify-center">
          <div class="text-center text-white">
            <h3 class="text-2xl font-bold mb-4">Ready to Transform Your Business?</h3>
            <p class="mb-6">Let's discuss how we can help you achieve your goals</p>
            <button class="bg-white text-blue-600 px-6 py-3 rounded-lg font-semibold hover:bg-gray-100">
              Get Started →
            </button>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ChevronLeft, ChevronRight, Lightbulb, Target, Users, Globe } from 'lucide-vue-next'
</script>

// BITZ-ITC-main/app/our-vision/page.tsx
'use client'

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ArrowRight, ChevronRight, Globe, Lightbulb, Target, Users, Mail, MessageSquare, Headphones } from 'lucide-react'
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@/components/ui/carousel"

export default function OurVision() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-navy text-white dark:bg-dark-gradient">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12 items-center">
              <div className="space-y-4">
                <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tighter">
                  Our Vision
                </h1>
                <p className="text-xl md:text-2xl text-gray-300">
                  Empowering businesses through innovative technology solutions and digital transformation.
                </p>
              </div>
              <div className="flex justify-center">
                <Carousel className="w-full max-w-[500px]">
                  <CarouselContent>
                    <CarouselItem>
                       <div className="relative w-full aspect-video bg-gradient-to-br from-[#000435] to-[#000a6b] rounded-3xl shadow-ios-lg flex items-center justify-center">
                          <Lightbulb className="h-24 w-24 text-white/80" />
                        </div>
                    </CarouselItem>
                     <CarouselItem>
                       <div className="relative w-full aspect-video bg-gradient-to-br from-[#000435] to-[#000a6b] rounded-3xl shadow-ios-lg flex items-center justify-center">
                          <Target className="h-24 w-24 text-white/80" />
                        </div>
                    </CarouselItem>
                     <CarouselItem>
                       <div className="relative w-full aspect-video bg-gradient-to-br from-[#000435] to-[#000a6b] rounded-3xl shadow-ios-lg flex items-center justify-center">
                          <Users className="h-24 w-24 text-white/80" />
                        </div>
                    </CarouselItem>
                  </CarouselContent>
                   <CarouselPrevious className="bg-white/20 hover:bg-white/30 text-white border-none" />
                  <CarouselNext className="bg-white/20 hover:bg-white/30 text-white border-none" />
                </Carousel>
              </div>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 bg-white dark:bg-navy-900 animate-fade-in">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <Badge className="bg-navy hover:bg-navy/90 rounded-full px-4 py-1 text-sm">Our Mission</Badge>
                <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tighter">
                  Transforming Businesses Through Technology
                </h2>
                <p className="text-lg md:text-xl text-gray-500 dark:text-gray-400 max-w-[900px]">
                  We are very committed to delivering innovative solutions that drive growth and efficiency
                </p>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
              <Card className="border-0 shadow-ios rounded-3xl hover:shadow-ios-lg transition-all duration-300">
                <CardContent className="p-8 flex flex-col items-center text-center space-y-4">
                  <div className="p-4 rounded-full bg-gray-100 dark:bg-navy/20">
                    <Target className="h-10 w-10 text-navy dark:text-white" />
                  </div>
                  <h3 className="text-2xl font-bold">Our Goals</h3>
                  <p className="text-lg text-gray-500 dark:text-gray-400">
                    To be the leading technology partner for businesses seeking digital transformation
                  </p>
                </CardContent>
              </Card>
              <Card className="border-0 shadow-ios rounded-3xl hover:shadow-ios-lg transition-all duration-300">
                <CardContent className="p-8 flex flex-col items-center text-center space-y-4">
                  <div className="p-4 rounded-full bg-gray-100 dark:bg-navy/20">
                    <Users className="h-10 w-10 text-navy dark:text-white" />
                  </div>
                  <h3 className="text-2xl font-bold">Our Values</h3>
                  <p className="text-lg text-gray-500 dark:text-gray-400">
                    Innovation, integrity, and excellence in everything we do
                  </p>
                </CardContent>
              </Card>
              <Card className="border-0 shadow-ios rounded-3xl hover:shadow-ios-lg transition-all duration-300">
                <CardContent className="p-8 flex flex-col items-center text-center space-y-4">
                  <div className="p-4 rounded-full bg-gray-100 dark:bg-navy/20">
                    <Globe className="h-10 w-10 text-navy dark:text-white" />
                  </div>
                  <h3 className="text-2xl font-bold">Our Impact</h3>
                  <p className="text-lg text-gray-500 dark:text-gray-400">
                    Creating lasting positive change in the businesses we serve
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 bg-gray-50 dark:bg-navy-950 dark:bg-dark-gradient animate-fade-in">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-12 items-center">
              <div className="space-y-4">
                <Badge className="bg-navy hover:bg-navy/90 rounded-full px-4 py-1 text-sm">
                  Our Approach
                </Badge>
                <h2 className="text-3xl md:text-4xl font-bold tracking-tighter">
                  How We Work
                </h2>
                <p className="text-lg text-gray-500 dark:text-gray-400">
                  Our methodology combines technical expertise with a deep understanding of business needs
                </p>
                <ul className="space-y-4">
                  <li className="flex items-start gap-4">
                    <div className="p-2 rounded-full bg-navy/10">
                      <span className="text-navy font-bold">1</span>
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">Understanding</h3>
                      <p className="text-gray-500 dark:text-gray-400">Deep dive into your business needs and challenges</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-4">
                    <div className="p-2 rounded-full bg-navy/10">
                      <span className="text-navy font-bold">2</span>
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">Strategy</h3>
                      <p className="text-gray-500 dark:text-gray-400">Develop tailored solutions to address your specific needs</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-4">
                    <div className="p-2 rounded-full bg-navy/10">
                      <span className="text-navy font-bold">3</span>
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">Implementation</h3>
                      <p className="text-gray-500 dark:text-gray-400">Execute solutions with precision and attention to detail</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-4">
                    <div className="p-2 rounded-full bg-navy/10">
                      <span className="text-navy font-bold">4</span>
                    </div>
                    <div>
                      <h3 className="font-bold text-lg">Support</h3>
                      <p className="text-gray-500 dark:text-gray-400">Provide ongoing support and optimization</p>
                    </div>
                  </li>
                </ul>
              </div>
              <div className="relative">
                <div className="aspect-square bg-gradient-to-br from-[#000435] to-[#000a6b] rounded-3xl shadow-ios-lg">
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="text-white text-center space-y-4 p-8">
                      <h3 className="text-2xl font-bold">Ready to Transform Your Business?</h3>
                      <p className="text-lg text-gray-300">Let's discuss how we can help you achieve your goals</p>
                      <Button className="bg-white text-navy hover:bg-gray-100 rounded-full text-base py-6 px-8">
                        Get Started
                        <ArrowRight className="ml-2 h-5 w-5" />
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
